version: '1.0'

services:
  optlite-webllm:
    build:
      context: ./optlite-webllm
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ai-model:
    build:
      context: ./AI-Model
      dockerfile: Dockerfile
    ports:
      - "5050:5050"

  jupyterlite:
    build:
      context: ./JupyterLite
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

