name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r optlite/requirements.txt
      - name: Build python wheel
        run: python setup.py bdist_wheel -d dist
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: optlite-build-${{ github.run_number }}
          path: ./build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: optlite-build-${{ github.run_number }}
          path: ./build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build
